name: openjmu_lite
description: A lite version of OpenJMU for essential function.

version: 0.1.4+6

environment:
    sdk: ">=2.2.2 <3.0.0"
    flutter: 1.5.4-hotfix.2

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cached_network_image: 1.1.1
    crypto: 2.1.2
    dio: 2.1.16
    event_bus: 1.1.0
    extended_tabs: 0.2.0
    fluttertoast: 3.1.0
    flutter_cache_manager: 1.1.1
    flutter_platform_widgets: 0.12.0
    flutter_qr_reader: 1.0.2
    flutter_svg: 0.12.4+2
    flutter_webview_plugin: 0.3.7
    intl: 0.15.8
    package_info: 0.4.0+6
    permission_handler: 3.2.2
    shared_preferences: 0.5.3+4
    url_launcher: 5.1.2
    uuid: 2.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/icons/
        - images/
    fonts:
        -   family: chocolate
            fonts:
                - asset: assets/fonts/chocolate.ttf
        -   family: ProductSans
            fonts:
                - asset: assets/fonts/ProductSans-Regular.ttf