name: openjmu_lite
description: A lite version of OpenJMU for essential function.

version: 0.2.4+16

environment:
    sdk: ">=2.5.0 <3.0.0"
    flutter: 1.9.1+hotfix.4

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    cached_network_image: 1.1.1
    crypto: 2.1.2
    cookie_jar: 1.0.1
    dio: 3.0.3
    dio_cookie_manager: 1.0.0
    event_bus: 1.1.0
    extended_tabs: 0.2.2
    fluttertoast: 3.1.0
    flutter_cache_manager: 1.1.1
    flutter_local_notifications: 0.8.2+1
    flutter_platform_widgets: 0.12.0
    flutter_qr_reader: 1.0.2
    flutter_svg: 0.14.1
    flutter_webview_plugin: 0.3.8
    notification_permissions: 0.4.0
    package_info: 0.4.0+6
    permission_handler: 3.2.2
    provider: 3.1.0
    shared_preferences: 0.5.3+4
    url_launcher: 5.1.2
    uuid: 2.0.2

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/icons/
        - assets/icons/appCenter/
        - images/
    fonts:
        -   family: chocolate
            fonts:
                - asset: assets/fonts/chocolate.ttf
        -   family: ProductSans
            fonts:
                - asset: assets/fonts/ProductSans-Regular.ttf